### ISSUE TITLE
Main app is not executable and DOS file format

### ISSUE THREAD

**Issue by nicmarti** [octo-online/reactive-audit#12]
- reactive-audit is not executable on Unix as a default
- file format is DOS, thus when you try to execute you get ^M errors

**Comment by yaciben** [comment]
Fixed in commits 847f55e3ff90fad4a663053a9ff7752d43c85742 and 39c17826074a05b3091f6e291b7fafa46f8fcc4a

**Comment by yaciben** [comment]
Needs a more powerful solution as conversion still remains in some conditions.
