### ISSUE TITLE
Issue in Bash script line 208

### ISSUE THREAD

**Issue by nicmarti** [octo-online/reactive-audit#13]
Check line 208 there is a 'framework' pasted in the definition of REACTIVE_AUDIT_HOME

declare REACTIVE_AUD**framework**IT_HOME="$(dirname "${BASH_SOURCE[0]}")/.."

**Comment by yaciben** [comment]
Fixed in commits 847f55e3ff90fad4a663053a9ff7752d43c85742 and 39c17826074a05b3091f6e291b7fafa46f8fcc4a
