### ISSUE TITLE
Unable to setup reactive-audit after download

### ISSUE THREAD

**Issue by Strydom** [octo-online/reactive-audit#16]
when using the `reactive-audit` command on a MAC after setting that `PATH` variable in `.bash_profile` i get this:
`-bash: /Users/cstrydom/Downloads/reactive-audit-agent/bin/reactive-audit: /bin/bash^M: bad interpreter: No such file or directory`

And if I use `source reactive-audit` i get:
```
: invalid signal specification
: invalid option
set: usage: set [--abefhkmnptuvxBCHP] [-o option] [arg ...]
: command not found
-bash: /Users/cstrydom/Downloads/reactive-audit-agent/bin/reactive-audit: line 2': syntax error near unexpected token `{
-bash: /Users/cstrydom/Downloads/reactive-audit-agent/bin/reactive-audit: line 2': `cleanup() {
```

**Comment by garethahealy** [comment]
@Strydom ; i am getting same. I needed to:

1. update bash shebang:
> #!/usr/bin/env bash

2. replace line endings
> perl -pi -e 's/\r\n|\n|\r/\n/g' reactive-audit

3. set REACTIVE_AUDIT_HOME in .bash_profile

Once thats done, i can run:

`localhost:~ garethah$ source reactive-audit
Now you can use the environment variable AUDIT_OPTS for launch Java program.
 set JAVA_OPTS=$AUDIT_OPTS
Add -DreactiveAudit=<yourfile>.properties to select a specific configuration.`

**Comment by medmes** [comment]
You should just set variable environment (REACTIVE_AUDIT_HOME) in order to run the command.

**Comment by Strydom** [comment]
Stale. Unsure if above helped or if i just abandoned.
